--- 
- hosts: webserver
  become: yes
  gather_facts: yes
  tasks: 
    - name: install java on ubuntu
      apt:
        name: openjdk-7-jre
        state: present
      when: ansible_os_family =="Debian"
   
    - name: install java on RedHat
      yum:
        name: java-1.6.0-openjdk
        state: present
      when: ansible_os_family =="RedHat"