--- 
- hosts: webserver
  become: yes
  gather_facts: yes
  tasks: 
    - name: installing java on ubuntu
      apt:
        name: "{{javaonubuntu}}"
        state: present
      when: ansible_os_family =="Debian"
   
    - name: installing java on RedHat
      yum:
        name: "{{javaonRedHat}}"
        state: present
      when: ansible_os_family =="RedHat"