---
- hosts: webserver
  become: yes
  tasks:
  - name: installing apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"
  - name: start apache2 server 
    service: 
      name: apache2
      state: started
    when: ansible_os_family =="Debian"   
  -  name: installing httpd
     yum:
      name: httpd
      state: present
     when: ansible_os_family =="RedHat"
  - name: start apache2 server 
    service: 
      name: httpd
      state: started
    when: ansible_os_family =="RedHat"